model_reasoning_effort = "high"
personality = "pragmatic"
model = "gpt-5.5"

notify = ["bash", "-lc", "afplay /System/Library/Sounds/Ping.aiff"]

[features]
web_search_request = true

[mcp_servers]

[mcp_servers.sentry]
url = "https://mcp.sentry.dev/mcp"

[projects."/Users/chiyuu/Documents/git/PraLoop"]
trust_level = "trusted"

[projects."/Users/tomohiro-kogawa/Documents/git/ansinsougi-admin-base"]
trust_level = "trusted"

[projects."/Users/tomohiro-kogawa/Documents/git/dotfiles"]
trust_level = "trusted"

[tui.model_availability_nux]
"gpt-5.5" = 4
